### PR TITLE
Remove references to removed modules for compatibility with PEG.js HEAD.

### PR DESCRIPTION
**Pull request by r3c**

### CODE REVIEW

**Comment by nylen** [comment]
Thanks for the PR!

Let's do a few more things here:

- Update the `pegjs` version in `package.json` to a specific version
- Clearly indicate the intended compatible `pegjs` version in the readme
- Get the build passing with this new version.

Let me know if you'd like help with any/all of those tasks.

**Comment by r3c** [comment]
Agreed about your last point, it should be fine after a rebase now that #5 is merged.

For your other points, problem is that pegjs had no release for the last 100+ commits, and this change makes phpegjs compatible with a version that was therefore not released yet (but it's still compatible with last release, no changes there). Do you think that's OK?

**Comment by r3c** [comment]
Superseeded by #7.

**Comment by nylen** [comment]
For future reference, it's not necessary to open a new PR.  Something like this should work regardless of what happened in your working tree:

```
# (commit your changes)
git checkout -B topic/pegjs-head
git push -f origin topic/pegjs-head
```

> but it's still compatible with last release, no changes there

This seems fine.  Which version is this? (edit: looks like `0.10.0` which this library is already using).

**Pull request closed without merging**
